### ISSUE TITLE
How to handle higher dimensional input Values?

### ISSUE THREAD

**Issue by ndrogers** [the-carlisle-group/APL2XL#10]
More discussion is needed to define valid input formats for range.Value. 

At present, only range.Value(s) of rank 2, depth 2 are supported. @PaulMansour @mkromberg Will there be a need support for higher rank arrays? Deeper nesting? What defines invalid input, and how should those inputs be handled?

**Comment by PaulMansour** [comment]
I do not think there is any need anything other than matrices of simple strings and scalar numerics.  In fact, I think I almost always use either an  array of strings or an array of numerics, and not a mixed array. For example, if I want to put a table with headers into Excel , I will define a range for the headers, and then a range for each column.
